version: '3.5'

networks:
  desafioNetwork:
    name: desafioNetwork
    driver: bridge

volumes:
  node_modules:
  databaseFiles_desafio:      

services:

  nginx_desafio:
    container_name: nginx_desafio
    hostname: nginx
    build: 
      context: ./nginx-proxy
      dockerfile: Dockerfile
    networks:
      - desafioNetwork
    ports:
      - "8080:80"
    depends_on:
      - nodeapp_desafio  

  nodeapp_desafio:
    container_name: nodeapp_desafio
    build:
      context: ./node-app
      dockerfile: Dockerfile
    volumes:
      - ./node-app:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - desafioNetwork
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - database_desafio

  database_desafio:
    container_name: database_desafio
    build:
      context: ./mysql-db
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - databaseFiles_desafio:/var/lib/mysql
      - ./mysql-db/scripts/:/var/lib/mysql/scripts
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root      
    networks:
      - desafioNetwork