version: '3.5'

networks:
  desafioNetwork:
    name: desafioNetwork
    driver: bridge

volumes:
  node_modules:

services:

  nginx_desafio:
    container_name: nginx_desafio
    hostname: nginx
    build: 
      context: ./nginx-proxy
      dockerfile: Dockerfile
    networks:
      - desafioNetwork
    ports:
      - "8080:80"
    depends_on:
      - nodeapp_desafio  

  nodeapp_desafio:
    container_name: nodeapp_desafio
    build:
      context: ./node-app
      dockerfile: Dockerfile
    image: nodeapp_desafio_init
    volumes:
      - ./node-app:/usr/src/app
      - ./environments:/usr/src/app/environments
      - node_modules:/usr/src/app/node_modules
    networks:
      - desafioNetwork
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - mysql_desafio


  mysql_desafio:
    image: mysql:${MYSQL_VERSION}
    container_name: ${DATABASE_CONTAINER_NAME}
    working_dir: /var/lib/mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - ./mysql/database:/var/lib/mysql
    env_file:
     - ./environments/dev.env
    networks:
      - desafioNetwork